services:
    web-server:
        build:
            dockerfile: php.Dockerfile
            context: .
        restart: always
        volumes:
            - "./src/:/var/www/html/"
        ports:
            - "8080:80"
        depends_on:
            mysql-server:
                condition: service_healthy

    mysql-server:
        build:
            dockerfile: Dockerfile
            context: ./database
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./database:/docker-entrypoint-initdb.d
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-uroot",
                    "-psecret",
                ]
            interval: 7s
            timeout: 7s
            retries: 20

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.1
        restart: always
        environment:
            PMA_HOST: mysql-server
            PMA_USER: root
            PMA_PASSWORD: secret
        ports:
            - "5055:80" #if you got getting port conflicts with phpmyadmin on port 5000, you can change (ie 5050)
        depends_on:
            mysql-server:
                condition: service_healthy

volumes:
    mysql-data:
