CREATE DATABASE market_database;

USE market_database;

CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY, First_Name VARCHAR(50) NOT NULL, Last_Name VARCHAR(50) NOT NULL, Email VARCHAR(100) NOT NULL UNIQUE, MD5_Password CHAR(32) NOT NULL, User_Image BLOB
);

CREATE TABLE Admins (
    Admin_ID INT AUTO_INCREMENT PRIMARY KEY, First_Name VARCHAR(50) NOT NULL, Last_Name VARCHAR(50) NOT NULL, Email VARCHAR(100) NOT NULL UNIQUE, MD5_Password CHAR(32) NOT NULL,
);

CREATE TABLE Comments{ 
    COMMENT_ID INT AUTO_INCREMENT PRIMARY KEY,  
    COMMENT_TEXT TEXT NOT NULL, 
    ITEM_ID INT NOT NULL,
    USER_ID INT NOT NULL , 
    DATE_TIME_ADDED DATETIME NOT NULL


    Foreign Key (USER_ID) REFERENCES USERS(USERS_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID)
} 


CREATE TABLE ITEMS (
    ITEM_ID INT AUTO_INCREMENT PRIMARY KEY, ITEM_NAME VARCHAR(100) NOT NULL, ITEM_DESCRIPTION TEXT NOT NULL, EXTERNAL_LINK VARCHAR(255), ITEM_IMAGE BLOB
);

CREATE TABLE STORE (
    STORE_ID INT AUTO_INCREMENT PRIMARY KEY,
    STORE_NAME VARCHAR(50) NOT NULL
)
-- IF A Item_price_entry per store exists, then the store sells it.
CREATE TABLE Item_Price_Entry (
    Item_Entry INT AUTO_INCREMENT PRIMARY KEY,
    STORE_ID INT NOT NULL,
    ITEM_ID INT NOT NULL,
    Item_Price FLOAT(4, 2) NOT NULL,
    Time_Updated DATETIME NOT NULL,


    Foreign Key (STORE_ID) REFERENCES STORE (STORE_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ITEM_ID),
);