name: Docker Image CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-mysql-server:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build the mysql-server Docker image
              run: |
                  docker build ./database --file ./database/Dockerfile --build-arg MYSQL_ROOT_PASSWORD=secret -p 3306:3306 --tag mysql-web-server

            - name: Start Database Container
              run: |
                  docker run -d --name mysql-web-server-container mysql-web-server
    build-web-server:
        runs-on: ubuntu-latest
        needs: build-mysql-server
        steps:
            - uses: actions/checkout@v3
            - name: Build the web-server Docker image
              run: |
                  docker build . --file php.Dockerfile --tag web-server

            - name: Start web-server container
              run: |
                  docker run -d --name web-server-container web-server

            - name: Execute PHPUnit tests
              run: docker exec web-server-container sh -c "phpunit --testdox tests/*"
