name: Docker Image CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Create Docker Network
              run: docker network create my_network

            - name: Build the mysql-server Docker image
              run: |
                  docker build ./database --file ./database/Dockerfile --tag mysql-web-server

            - name: Start Database Container
              run: |
                  docker run --network my_network -d --expose=3306 -v ./database:/docker-entrypoint-initdb.d -e "MYSQL_ROOT_PASSWORD=secret" --name mysql-server mysql-web-server

            - name: Build the web-server Docker image
              run: |
                  docker build . --file php.Dockerfile --tag web-server

            - name: Start web-server container
              run: |
                  docker run --network my_network -d -v ./src/:/var/www/html/ --name web-server web-server

            - name: Execute AdminManagement tests
              run: docker exec web-server sh -c "phpunit --testdox tests/Admin_Management_Test.php"

            - name: Execute Comments tests
              run: docker exec web-server sh -c "phpunit --testdox tests/CommentsTest.php"

            - name: Execute ItemInfo tests
              run: docker exec web-server sh -c "phpunit --testdox tests/Item_info_Test.php"

            - name: Execute UserManagement tests
              run: docker exec web-server sh -c "phpunit --testdox tests/User_Management_Test.php"
