name: Docker Image CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
    build-and-test:
        runs-on: ubuntu-latest

        services:
            mysql-server:
                image: ./database
                env:
                    MYSQL_ROOT_PASSWORD: secret
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping -h localhost"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5

            web-server:
                image: ./php.Dockerfile
                ports:
                    - 80:80
                options: --name web-server-container

        steps:
            - uses: actions/checkout@v3

            - name: Build the web-server Docker image
              run: docker build . --file php.Dockerfile --tag web-server

            - name: Start web-server container with the custom image
              run: docker run -d --name web-server-container -p 80:80 web-server

            - name: Execute commands in the MySQL service container
              run: docker exec mysql-server mysql -uroot -proot -e "SHOW DATABASES;"

            - name: Execute PHPUnit tests in the web-server container
              run: docker exec web-server-container sh -c "phpunit --testdox tests/*"
